### ISSUE TITLE
Export / Import model list 

### ISSUE THREAD

**Issue by Mush-r00m** [0xboobface/ctbrec#100]
Earlier, 1.12 stopped recording chaturbate models, would only tick the box for them being online.
I closed the program and launched again same issue, not sure how long this had been going on since i was away from my computer most of the day, also not sure if it was a fluke/temp situation. However i decided to update to 1.13, when launching it gave me a warning it couldnt load the previous settings and made a back up of them and launched with default setting with no model list.

i tried to edit the settings.json and add all 158 models but it refused to launch with the setting file.
It would be useful to be able to export models. So for example i could export model list before an update incase something like this happens again i can easily import them.

**Comment by 0xboobface** [comment]
> made a back up of them

I added that just for these situations. Good thing I did that.

Without log and settings file I can only suspect, what went wrong. Please attach the file here or send them to 0xboobface at gmail. **Don't forget to remove your credentials!**

**Comment by Mush-r00m** [comment]
Unfortunately i have already deleted the ctbrec folders and started fresh & added all the models back manually

**Comment by 0xboobface** [comment]
> It would be useful to be able to export models. So for example i could export model list before an update incase something like this happens again i can easily import them.

This is basically, what happens when saving and loading the config file. An import / export would do the same thing, only without all the other settings. I would rather fix the problem with the settings than implement that. Closing this for now.
