### ISSUE TITLE
A JNI error has occured

### ISSUE THREAD

**Issue by Qwatuz** [0xboobface/ctbrec#102]
Running Windows 7 64-bit and 64-bit Java (re-installed it to make sure).

The older versions of CTBrec worked fine, but recently they started having errors when opening streams on Chaturbate, for example:

https://i.imgur.com/86JaFdf.png

If I keep trying to open the stream eventually it will.

And if I run the latest version of CTBrec I get this error:

https://i.imgur.com/sowz1iF.png

Then after clicking OK this pops up:

https://i.imgur.com/4SlX5UW.png

**Comment by 0xboobface** [comment]
> The older versions of CTBrec worked fine, but recently they started having errors when opening streams on Chaturbate, for example:
> 
> https://i.imgur.com/86JaFdf.png
> 
> If I keep trying to open the stream eventually it will.

This was fixed in 1.13.0, see #87 



> And if I run the latest version of CTBrec I get this error:
> 
> https://i.imgur.com/sowz1iF.png
> 
> Then after clicking OK this pops up:
> 
> https://i.imgur.com/4SlX5UW.png

Do you also get these errors, if you use the JRE bundle?

**Comment by RedRhumRedRhum** [comment]
I get this when trying to follow rooms on CB (on any version)
https://imgur.com/a/ObPGIy1

Started to happen last Wednesday.

**Comment by 0xboobface** [comment]
@RedRhumRedRhum Your error is completely unrelated. Why are you posting it here instead of a new bug report? You are getting is error, because you are not logged it.

**Comment by Qwatuz** [comment]
Fantastic @0xboobface, the JRE bundle works perfectly. It's strange because I used to make use of the win64.zip download but now JRE seems to be the one to choose!

Thank you very much for your hard work! Much appreciated.

**Comment by 0xboobface** [comment]
May I ask, which exact Java version you were using?
