### ISSUE TITLE
Issue with server 

### ISSUE THREAD

**Issue by forsomefun2** [0xboobface/ctbrec#105]
**Describe the bug**

**To Reproduce**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Ctbrec Version 1.13
 - Server

**Log**
/home/xxxxxxxxx/ctbrec/ctbrec/server.sh: 3: /home/xxxxxxxxxxx/ctbrec/ctbrec/server.sh: pushd: not found
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)
Error: Could not find or load main class ctbrec.recorder.server.HttpServer
Caused by: java.lang.ClassNotFoundException: ctbrec.recorder.server.HttpServer
/home/xxxxxxxxxxxxxxx/ctbrec/ctbrec/server.sh: 7: /home/xxxxxxxxxxxxx/ctbrec/ctbrec/server.sh: popd: not found

Not sure what I am doing wrong here. 
From what  understand I need to run the server and then connect via my windows computer.

My server is a offsite ssh server. 
I am using windows to access it.

**Comment by 0xboobface** [comment]
That's a bug in the script. In the first line replace /bin/sh with /bin/bash, then it should work.
