### ISSUE TITLE
Installed JRE not detected

### ISSUE THREAD

**Issue by the0perator18** [0xboobface/ctbrec#11]
What method are you using to determine Java is installed?  I have it installed:

> C:\Users\myuser>java -version
> java version "1.8.0_181"
> Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
> Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

But when I run the .exe it says the runtime is required, then takes me to the java website.

**Comment by Mush-r00m** [comment]
Not sure what the issue is, But have you tried downloading the version that includes java?
https://github.com/0xboobface/ctbrec/releases/download/1.2.0/ctbrec-1.2.0-win64-jre.zip

**Comment by 0xboobface** [comment]
Not sure why this happens. I'm using launch4j to generate the exe. Maybe it helps to set the JAVA_HOME environment variable and let it point to your Java installation. If that does not help, try the package with bundled JRE as Mush-r00m said. That should work in any case.
