### ISSUE TITLE
Minimum file size

### ISSUE THREAD

**Issue by Fastfinguh** [0xboobface/ctbrec#111]
Specify the minimum file size the recording should be. If it doesn't meet the size requirements, remove the file - useful when models go in and out of privates, or go away and come back (prevents a whole lot of small files being stored).

if stats.size <= config.minfilesizemb * 1048576
unlink the source file else move the file to it's destination folder

**Comment by 0xboobface** [comment]
I was thinking about a feature like that, too. With 1.14 you could achieve that functionality with a script, which is run when a recording is finished. I'm a bit undecided, if I should add that as a built-in function or not.

**Comment by Fastfinguh** [comment]
That's true. But still. Adding a checkbox would be super ease of use + it's an extra feature which is always nice. Check the mockup picture I made, sorry for the font I tried my best at estimating the right font, I know it's not the exact same one. I put the min. file size under the "Recorder" section - last option

https://imgur.com/0LBTfO5

**Comment by Fastfinguh** [comment]
Didn't even think about length. Maybe with xuggler. Thank you for checking if there's a possibility.

**Comment by 0xboobface** [comment]
Added in ceb7c07
