### ISSUE TITLE
Myfreecams: nProfileUserId

### ISSUE THREAD

**Issue by jamesjonesfor3** [0xboobface/ctbrec#113]
Models have a nProfileUserId in the page source of their profile page. Currently if a model changes her username, ctbrec will screw up and start recording a random model.

Feature request: 
- new column in the Recording tab: nProfileUserId
- upon adding a model's username to the Recording tab, auto grab the nProfileUserId 
- capture streams via the nProfileUserId instead to avoid name changing issues

**Comment by 0xboobface** [comment]
ctbrec actually takes the models uid into account. I added that in 1.7.0. There must be a bug, which causes that. Which version were you using?

**Comment by 0xboobface** [comment]
I think, I found the problem. The next version will contain a fix, which hopefully solves this problem.
Fixed in dc8a4d4.
