### ISSUE TITLE
Add setting for thumbnail / overview refresh rate

### ISSUE THREAD

**Issue by delleps** [0xboobface/ctbrec#123]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 0xboobface** [comment]
Why? What's the problem with the current 10 seconds?

**Comment by codexhard** [comment]
Thumbnails refreshing every 10 seconds makes my windows 7 running on Synology VM almost freeze! it would be nice if we can change or stop refreshing.

**Comment by 0xboobface** [comment]
There is a setting "Update thumbnails". Did you try that? The models are still updated, but not the thumbnails. That should make it easier on the cpu

**Comment by delleps** [comment]
10 seconds between refreshes is a bit fast IMO and can tax lesser systems. I've been blocked from CBT on a couple occasions where I was refreshing too often (with another app, since superseded by yours). Another reason is you've added the ability to double-click on thumbs to open a player. At 10 sec refresh it's often like whack-a-mole where it refreshes as you're double-clicking and you get a random model.

**Comment by delleps** [comment]
I was under the assumption that the model list polling was for recording and thumbnail refresh was separate. If not, I guess a single parameter could work for both.

**Comment by delleps** [comment]
BTW, a smashing job on the app!

**Comment by 0xboobface** [comment]
The online check for the recordings and the refresh rate of the thumbnails are separate. For the online check, there already is an adjustable setting under "Recorder". I'm gonna add one for the thumbnails, too. But only one for all sites.
