### ISSUE TITLE
Minimize to tray option

### ISSUE THREAD

**Issue by nim56** [0xboobface/ctbrec#125]
Suggestion: a minimize to tray option, maybe a box to tick in the options so that when you close ctbrec it minimizes it to tray like this:
![untitled](https://user-images.githubusercontent.com/45295620/50229442-9fb0d280-03aa-11e9-8a37-ee457f0d9821.jpg)
Or a button like this if that's possible: 
![untitled](https://user-images.githubusercontent.com/45295620/50228527-78590600-03a8-11e9-9df8-1ae6b618a42f.jpg)

**Comment by RedRhumRedRhum** [comment]
You can always use the program Tray It! to send programs to the tray if you are using Windows.

**Comment by nim56** [comment]
I can use that if can save 0xboobface some time no problem :thumbsup:.
