### ISSUE TITLE
Add clear option into Recordings tab

### ISSUE THREAD

**Issue by Hunterek** [0xboobface/ctbrec#128]
It would be nice to see clear option into this tab, cause when you want clear finished download you have got only delete option. Check all, clear options without deleteting download records would be nice

**Comment by 0xboobface** [comment]
I don't complete get what you are saying. Can you please explain what you want to achieve?

**Comment by Hunterek** [comment]
When you try clean all downloaded files without deleting them you should click on right mouse button and choose clean or clear option. They are only delete option right now. BTW got some today bug on recordings tab (in linux version) in screenshot more info
![2018-12-27-003614_1920x1080_scrot](https://user-images.githubusercontent.com/17682334/50459829-a5d91d00-096f-11e9-94e5-171454cf431b.png)

**Comment by 0xboobface** [comment]
If I understand you correctly you want to remove the finished recordings from the recordings tab, is that right? At the moment, I don't plan on implementing a feature like this. The recordings tab just lists all recordings, which are found in the configured recording directory. If you want to clear finished recordings, you have to move the files to another directory.
There is a similar feature request: #112
