### ISSUE TITLE
convert mp4

### ISSUE THREAD

**Issue by snickerp** [0xboobface/ctbrec#130]
Do I need to change the config so the post processing script can work

every model has there own folder, and then a folder with the date. I'm using the linux server setup. Did I miss something

as ffmpeg keeps saying that the file is a directory

**Comment by 0xboobface** [comment]
Did you use the pp.sh, which comes with the client? That does not work for the server, since the server records the stream as it is delivered (in several small segments) whereas the client creates only one large file.
The post-processing script for the server gets the directory as a parameter, so have to adjust the script to list either the segments or alternatively you can pass the playlist to ffmpeg.

```
#!/bin/bash

# $1 parent directory (model name)
# $2 directory (date)
# $3 model name
# $4 site name
# $5 unixtime

# get the filename without path
FILE=$(echo $2/playlist.m3u8)

# format unixtime to human readable
TIME=$(date --date="@$5" +%d.%m.%Y_%H:%M)

# define filename of end result
MP4=$(echo "/tmp/$4_$3_$TIME.mp4")

# remux ts to mp4
ffmpeg -i $FILE -c:v copy -c:a copy -f mp4 $MP4

# delete the directory of the recording
rm -r $1
```

**Comment by snickerp** [comment]
This works a lot better since I'm not planning on playing these off the server.  
Thanks for showing the necessary changes required

**Comment by snickerp** [comment]
This also works for ffmpeg
 -c copy -copyts -start_at_zero -analyzeduration 3000000000 $MKV

it seems like your need a player like potplayer to play them anyways
Windows default player is very jumpy I am going to test a larger file now to see how it players.

**Comment by iyyp** [comment]
I'm not planning on playing these off the server, but the process of generating a playlist takes a lot of time on my server.
How to create only one large file like the client?

**Comment by 0xboobface** [comment]
At the moment there is no possibility to switch off the playlist generation. I'm gonna add an issue for that.

**Comment by iyyp** [comment]
Thanks for taking the time consider my suggestions.
