### ISSUE TITLE
Combine video files on server

### ISSUE THREAD

**Issue by zoeysama** [0xboobface/ctbrec#134]
I noticed that on server  the recording is stored as many .ts files and a .m3u8 playlist
and only can be combined while downloading with local client.

However my server's network is not stable,so downloading progress always stuck.
Can video clips be combined on server first ?
So i can combine clips  on server first and  use http or anything else to download the big combined  file , 
and that i can use  some download tools with feature of  resume from break point.

Please forgive me for my poor English.

**Comment by 0xboobface** [comment]
You can use the post-processing feature to combine the files or do whatever you like. See #130
