### ISSUE TITLE
systemd startup script

### ISSUE THREAD

**Issue by forsomefun2** [0xboobface/ctbrec#138]
What would be a good way to setup a systemd script for this program. 

I've tried pm2 but it never starts the program, so something else might be needed it seems

**Comment by 0xboobface** [comment]
I always start the server manually, but I will have a look at it.

**Comment by 0xboobface** [comment]
I added a wiki page for that: https://github.com/0xboobface/ctbrec/wiki/Running-the-ctbrec-server-with-systemd

**Comment by forsomefun2** [comment]
Thank you that was a quick turn around

I've seen your script for post processing and conversion.

How would you do this mannually. I have a few files that must have not converted. Because I closed the program.

**Comment by 0xboobface** [comment]
You basically run the ffmpeg command inside the directory of the recording

`ffmpeg -i playlist.m3u8 -c:v copy -c:a copy -f mp4 merged.mp4`

**Comment by forsomefun2** [comment]
That works I have one more quick question
I think I could figure something for a loop into directories but this requires also going into subdirectories of subdirectories

for d in /home/xxxxxxxxx/streamdvr/ctbrecordings/.*; do (cd "$d" && for d in ./*/ ; do (cd "$d" && ffmpeg -i playlist.m3u8 -c:v copy -c:a copy -f mp4 merged.mp4); done); done

works but is there a way to get the command to go to into the date folders as well 
starting

**Comment by 0xboobface** [comment]
For bash, untested!

`for i in $(find /home/xxxxxxxxx/streamdvr/ctbrecordings -name 'playlist.m3u8'); do pushd $(dirname $i); ffmpeg -i playlist.m3u8 -c:v copy -c:a copy -f mp4 merged.mp4; popd; done`
