### ISSUE TITLE
Program does not move merged files to the chosen destination

### ISSUE THREAD

**Issue by idroccolo** [0xboobface/ctbrec#14]
Even if I select another destination for the merged files, everyting remains in the recordings directory.

**Comment by 0xboobface** [comment]
I can't reproduce this bug neither on Windows 10 nor on Linux. Does this problem occur only occur occasionally or everytime? If it occurs everytime, could you please delete the log file ctbrec.log before starting ctbrec and then do one short recording? Maybe we can find something in the logfile then.

**Comment by idroccolo** [comment]
Sure! As soon as I can.

**Comment by idroccolo** [comment]
Please, tell me where is ctbrec.log supposed to be.

**Comment by 0xboobface** [comment]
The ctbrec.log should be in the same directory as ctbrec.exe. If it is not there, try to open the folder containing ctbrec.exe and then starting ctbrec by double clicking ctbrec.exe. The log should be created then.

**Comment by idroccolo** [comment]
It does not create any file inside the folder in which the EXE is. Not when opening neither when closing.

**Comment by 0xboobface** [comment]
That's odd. I just checked it on Windows 10 64 Bit. I downloaded the zip with the bundled JRE, extracted it in the Downloads folder and double clicked the ctbrec.exe. The ctbrec.log file then occurred after a second or so.

Which operating system are you using? And where did you extract ctbrec? Could it be a permission problem?

**Comment by SomebodyFromtRO** [comment]
I have the same problem. not sure if this can help but logs show something like this

> ERROR [PostprocessingD:\Program Files (x86)\CTB\chaturbate\vicky_berry\2561-08-28_17-44] c.r.LocalRecorder [LocalRecorder.java:336] Couldn't move merged file to merge dirctory C:\Users\Jacky\Desktop\ctbrec\test

> ERROR [PostprocessingD:\Program Files (x86)\CTB\chaturbate\vicky_berry\2561-08-28_17-44] c.r.LocalRecorder [LocalRecorder.java:345] Couldn't delete directory D:\Program Files (x86)\CTB\chaturbate\vicky_berry\2561-08-28_17-44

> java.io.IOException: Couldn't delete all files in D:\Program Files (x86)\CTB\chaturbate\vicky_berry\2561-08-28_17-44
> 	at ctbrec.recorder.LocalRecorder.delete(LocalRecorder.java:586)
> 	at ctbrec.recorder.LocalRecorder.merge(LocalRecorder.java:343)
> 	at ctbrec.recorder.LocalRecorder.access$1400(LocalRecorder.java:41)
> 	at ctbrec.recorder.LocalRecorder$2.run(LocalRecorder.java:305)

^that is all the logs show

and here is full logs from past few days if that help: https://pastebin.com/yVS3GH7d

Anyway, just want to say THANK YOU for this project. Great work!

**Comment by 0xboobface** [comment]
I suspect a file handle not getting released. On windows, that locks files, so that they can't be moved or deleted etc.

In your case it could also be, that you are recording to a directory inside of Program Files (x86), which might lead to permission problems.

I have to do some testing on Windows.

BTW.: Are you a time traveller? Your system clock looks like it ;)

**Comment by SomebodyFromtRO** [comment]
Oh well just changed from Program Files (x86) to other directory and it works! 
Thank you Mr.boobface. My fap experience is now fulfilled xD

**Comment by 0xboobface** [comment]
@idroccolo I just released 1.4.1, which should be a bit more robust when it comes to generating the playlist and merging the files. Please try the new version and see, if you are still having the same problems.

**Comment by 0xboobface** [comment]
> not a time traveller. It's a Buddhist calendar

@SomebodyFromtRO Aha! Very interesting! Nice to know, that the app works with a different calendar, too. Glad we could fix your issue.

**Comment by 0xboobface** [comment]
Version 1.5.0 does the whole segment merging while downloading. So this feature is obsolete.
