### ISSUE TITLE
Localhost

### ISSUE THREAD

**Issue by ddavidle6** [0xboobface/ctbrec#143]
CMD doesn't update automatically regarding recordings, and as a result, the program doesn't record unless I hit a key. Possible reason: program still assumes model is online even though they have been offline. (ver 1.16)

**Comment by 0xboobface** [comment]
What do you mean with CMD does not update? Which site was the model from?

**Comment by ddavidle6** [comment]
model was from chaturbate. so usually with cmd, it would list the model's recording quality and it would create a folder. however, if cmd pauses, i would have to press space (in the end, the model doesn't get recorded since by the time i found out the cmd has been paused, they're offline)

**Comment by 0xboobface** [comment]
This is a flaw of the windows command prompt. As you as you mark / select text in the command window, the whole process is blocked/paused. Once you right-click to remove the selection, the process is resumed. As I said, this is a problem with the windows command prompt and is unrelated to ctbrec. You can thank Microsoft for developing a horrific shell :wink:
