### ISSUE TITLE
Unable to record chaturbate.I can see the preview of chaturbate models except recording them.

### ISSUE THREAD

**Issue by fhxyl123** [0xboobface/ctbrec#145]
Dear  0xboobface, here are my descriptions of  the problem. The Ctbrec cannot record Chaturbate rencently (happens less than one week ago), but I still cannot find where the problems are. I am looking for your help, sincerely. 

**Describe the bug**
Unable to record chaturbate while others  like bongacams are ok.  Curiously,  I can still see the preview of chaturbate models except recording them.

**background**
I am from China mainland. As you know, I have no access to the website "www.chaturbate.com" because of Internet Firewall. So I used to change the site setting to "www.cbcamgirls.com", and the recording work went very well. But recently the site  "www.cbcamgirls.com" was blocked, too. Then I change the site to "www.homecamgirl.com". Curiously, I can only see the preview  except recording.

**Desktop (please complete the following information):**
 - OS: [Windows10 1809]
 - Ctbrec Version [1.16.0 JRE]

**Log**
[ctbrec.log](https://github.com/0xboobface/ctbrec/files/2754966/ctbrec.log)
  (Ctbrec Version1.16.0)

![image](https://user-images.githubusercontent.com/45901315/51112578-17530f80-183a-11e9-8606-4ad787da451a.png)

![image](https://user-images.githubusercontent.com/45901315/51111877-8a5b8680-1838-11e9-9c90-c34ac7d25f2e.png)

**Comment by 0xboobface** [comment]
I just tested it with www.homecamgirl.com and recordings work fine for me. Nevertheless, the error message 405 indicates, that the site you are using isn't a perfect "copy" of chaturbate and behaves differently than the original site. There is nothing I can do about it. I guess you have to find another way to breach the great chinese wall.
