### ISSUE TITLE
Personal Messaging

### ISSUE THREAD

**Issue by OdessaBoy** [0xboobface/ctbrec#148]
Is it possible to send you a non public personal message with potentially useful information which may assist with an Open Issue?  If so, how please?

If it is not possible currently, maybe a Feedback button on the Settings Tab could be added to enable secure, one-way submission of bugs, requests and feedback.

**Comment by 0xboobface** [comment]
Yeah, Github really is missing something to communicate. You can contact me via 0xboobface at gmail or @ctbrec on mastodon
