### ISSUE TITLE
Select quality of an already added model

### ISSUE THREAD

**Issue by idroccolo** [0xboobface/ctbrec#15]
Could you add an option in the right-click menu to edit the recording quality of a model from the "Recording" list? It is a bit annoying to eventually delete and add again a model just to edit the wanted rec quality.

**Comment by 0xboobface** [comment]
This will be in the next version. But you can only switch the resolution, when the model is online, because otherwise the information, which resolutions are available, is not available. I hope this still helps a little bit.
