### ISSUE TITLE
Can't run the program 

### ISSUE THREAD

**Issue by lordmaker** [0xboobface/ctbrec#152]
The program wont run,this happened after I updated to java se 11. The program is stuck in the loading screen.

![screenshot_1](https://user-images.githubusercontent.com/46866270/51487052-9e583880-1da2-11e9-9a49-322d7a42cecc.png)

**Comment by 0xboobface** [comment]
You are using the jre bundle. The jre bundle is always using the bundled jre. It does not matter, if another Java version is installed or not. The freeze has to have another reason. What does the log say?

**Comment by lordmaker** [comment]
![screenshot_2](https://user-images.githubusercontent.com/46866270/51489665-47099680-1da9-11e9-9545-7bf989b5c6b9.png)

**Comment by 0xboobface** [comment]
You computer seems to be have its own mind. You can try to reset the configuration completely. As in the other ticket:
* open %appdata%
* delete or rename both directories starting with ctbrec

This will do a "factory reset"

**Comment by lordmaker** [comment]
I fixed that issue, the only issue I still have is the livejasmine one.
