### ISSUE TITLE
Not able to record Livejasmin

### ISSUE THREAD

**Issue by nolesc230** [0xboobface/ctbrec#153]
Great program, just ran into this bit of an issue. I get this on all Livejasmin models. All other sites work good.

Livejasmin will not record

![error](https://user-images.githubusercontent.com/46108047/51503966-d01dcf00-1da3-11e9-9a14-50f7741890b4.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Ctbrec Version [e.g. 1.17.1 JRE]
 - Standalone

**Log*
```
java.io.IOException: Couldn't download segment
	at ctbrec.recorder.download.MergedHlsDownload.start(MergedHlsDownload.java:158)
	at ctbrec.recorder.LocalRecorder$2.run(LocalRecorder.java:202)
Caused by: java.io.IOException: Response was not successful: https://www.livejasmin.com/en/stream/hls/free/AlesyaSky
{"success":false,"data":[]}
```

**Comment by 0xboobface** [comment]
Does it work sometimes or does it not work at all? I sometimes get this error, when I try to start the player, but the recordings work fine.

**Comment by nolesc230** [comment]
I get this error every time. No successful recordings from Livejasmin.

**Comment by lordmaker** [comment]
you cant record and I cant even open the livejasmine tab, lol something is not working here :O

**Comment by Fastfinguh** [comment]
Try recording from the recordings tab. In the model box type LiveJasmin:model - That works for me.

**Comment by lordmaker** [comment]
> Try recording from the recordings tab. In the model box type LiveJasmin:model - That works for me.

thanks, that also works for me.

**Comment by 0xboobface** [comment]
@Fastfinguh Thanks for the hint.

**Comment by nolesc230** [comment]
Tried typing a models name in the recordings tab. Didn't work for me. So far I have tried deleting the browser folder in Appdata and deleting the cookies. Tried on another Windows 10 machine and a Windows 8 machine. Same results on both. Created another Livejasmin account just for kicks and then had the browser not closing issue. Turning off my firewall didn't help.

**Comment by M1h43ly** [comment]
No idea how helpful this will be, but have been playing around with the streamURL to find it, so far this works:

GET https://api-gateway.dditsadn.com//v1/stream/performers/{modelname}/streams/free/formats/hls?session=g2342e94f32b96a9e0f82ddbb111851a2&brandId=jasmin


Response:

`{
    "data": {
        "url": "https://ip-185-13-90-61.dditscdn.com/edge/{modelname}-stream_864_480_850-1548246908960/{modelname}-stream_864_480_850/playlist.m3u8?token=RFYxrbPu5ERE65xlXW-8c4AAi07Uap8OV-Y6xC-7JSiL149ESjru0PsFSUecm8y5AGkFhcoa4xLRn-uaiWjcLs-BLYHJmsrRaxHm595PF5E6enz15b261JQaBHyc-5CeBdIVIxMc2AdCRJxa-0lirkXm9WToIrc6YODU44GTuYVIJgnj-l_EjViQTfjO1Hv-R4OgrmB9UpWJ3D3D-Q36v3ba_aUOLdgQ_JHmGZS8R1ZRA80IbGLrNK1uVUyGDrRe1HGddY0QT1f1q1HFSYiu7c0OUWmwRxcSnsaz0KpNaDEg",
        "token": "RFYxrbPu5ERE65xlXW-8c4AAi07Uap8OV-Y6xC-7JSiL149ESjru0PsFSUecm8y5AGkFhcoa4xLRn-uaiWjcLs-BLYHJmsrRaxHm595PF5E6enz15b261JQaBHyc-5CeBdIVIxMc2AdCRJxa-0lirkXm9WToIrc6YODU44GTuYVIJgnj-l_EjViQTfjO1Hv-R4OgrmB9UpWJ3D3D-Q36v3ba_aUOLdgQ_JHmGZS8R1ZRA80IbGLrNK1uVUyGDrRe1HGddY0QT1f1q1HFSYiu7c0OUWmwRxcSnsaz0KpNaDEg",
        "node": "lubet",
        "stream-name": "stream_864_480_850"
    }
}`

Adding parameter to the request &streamName=stream_1280_720_2000 returns the following:

`{
    "data": {
        "url": "https://ip-185-13-90-61.dditscdn.com/edge/{modelname}-stream_1280_720_2000-1548246988983/{modelname}-stream_1280_720_2000/playlist.m3u8?token=RzUHL1XAVDmfseZbjDB9RD6otyzys8YDb1bjN3Ripjall86ibCUtv-MTXW4s3jUrGo-Mq-Tv7I3lAA_5IVYSGN1aEmcgSS64YWq0_bJdDq_IaNvDr2toET_J3gup5GdyhcmKYVaxeBCmwg7nerKYZdPVZ9rA_J0Q2YA04SMYf9jFgqCM2zL5VF8z2JO_zXaqfU98-Fpe7F2UqZOq8MwFZh7cBUpOiKj2a10M-uPPmWPqWWnSqVveg-Pq7XLIgZm7FzM2QDPMrhZvMkxvLOjyV0Kfve98Rw205Ez8pih5I_qja6DNGI6DRsotte24hzqHU",
        "token": "RzUHL1XAVDmfseZbjDB9RD6otyzys8YDb1bjN3Ripjall86ibCUtv-MTXW4s3jUrGo-Mq-Tv7I3lAA_5IVYSGN1aEmcgSS64YWq0_bJdDq_IaNvDr2toET_J3gup5GdyhcmKYVaxeBCmwg7nerKYZdPVZ9rA_J0Q2YA04SMYf9jFgqCM2zL5VF8z2JO_zXaqfU98-Fpe7F2UqZOq8MwFZh7cBUpOiKj2a10M-uPPmWPqWWnSqVveg-Pq7XLIgZm7FzM2QDPMrhZvMkxvLOjyV0Kfve98Rw205Ez8pih5I_qja6DNGI6DRsotte24hzqHU",
        "node": "lubet",
        "stream-name": "stream_1280_720_2000"
    }
}`


Was done as guest user emulating mobile and adding the "url" to VLC  plays the stream

**Comment by 0xboobface** [comment]
@M1h43ly Nice! I will check this out. It looks very promising.

**Comment by 0xboobface** [comment]
@lordmaker, @Fastfinguh, @nolesc230 I double-checked the code, because I wasn't sure about it. Adding the model with the input field and adding the model from thumbnail overview does the same thing. From my point of view, it worked by chance. Can you confirm, that it works everytime, if you use the input field? Because then I have to go into the very details and compare the differences at runtime.

**Comment by 0xboobface** [comment]
I uploaded version 1.17.1, which uses M1h43ly's URLs and should work much better and without having to enter credentials.

**Comment by nolesc230** [comment]
Fixed my issue. Thanks
