### ISSUE TITLE
True Headless Record Master

### ISSUE THREAD

**Issue by nrk666** [0xboobface/ctbrec#160]
It's clear you've put some thought into the server/client model for this, however I from reading a couple other semi-related issues I think one request like this (#48 maybe?) got sidetracked. 

I'd like to see the Record Master run headless (no GUI window) with the option for clients to connect to it in a more lightweight server option. So, the "Record Master" doesn't open up the browser windows, it just opens up a port for clients to connect and if some client selects a model for recording, the "Record Master" stores/keeps that configuration and does all the recording with the output saved on the record master for later retrieval (via client or other players). Also, if the client disconnects, the "Record Master" remembers the selections and keeps on recording models. So, all configs/recordings whatever remain on the "Record Master" end and clients can be used to adjust recordings/models/whatever and playback if wanted. 

If I try to start the ctbrec.sh on a remote server with no X windows running, it dies because it can't find "DISPLAY" (which is expected, I don't have X display running). I'd like to see the X windows requirement for the server end be optional. Let the server start in a headless option (no browser window) and then users can use any client they want to connect to it for configuration and selecting models using the browser on the client side. 

An android/tablet client would be pretty cool too, but that might be a stretch.

**Comment by 0xboobface** [comment]
> If I try to start the ctbrec.sh on a remote server

Here is your problem. You try to start the client as the server. Download the server package and run that. Then you get all the things you described in your post.

**Comment by nrk666** [comment]
Ah, I didn't even see the server portion, I only downloaded the linux-jre.zip release.
