### ISSUE TITLE
Add support for HTTP proxy

### ISSUE THREAD

**Issue by AlexeyFinder** [0xboobface/ctbrec#17]
Tell me please. Where can I find this list with the models?
And also. In the settings, I found a way to play the VLC. The record goes through it and I need to install it?

**Comment by AlexeyFinder** [comment]
Soorry me, please, it's me stupid.
In my country, Charturbate is blocked and your program could not start. I installed VPN on the PC and it was all good.
Could you add a proxy function?

**Comment by idroccolo** [comment]
Maybe you should try to simply change the DNS with a free one, maybe with 1.1.1.1 and 1.0.0.1 (cloudflare).

**Comment by 0xboobface** [comment]
Proxy support will be available in the next version.
