### ISSUE TITLE
Is there a way to load different settings.json on windows?

### ISSUE THREAD

**Issue by kingofipl** [0xboobface/ctbrec#172]
Hi,

Is there a way to run different settings.json if you want to run more then one instance of the program on windows?

**Comment by bj73** [comment]
See [here](https://github.com/0xboobface/ctbrec/issues/65#issuecomment-439608911)

Just duplicate the CTBRec directory contents and add a ctbrec.l4j.ini file with the path to a settings.json file.

eg. I have three folders with CTBRec and each of the ctbrec.l4j.ini files has:

-Dctbrec.config.dir=.\conf

So it looks in the conf directory under the current CTBRec directory for the settings.

**Comment by kingofipl** [comment]
Ah, thank you! Worked.
