### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by pbradjr99** [0xboobface/ctbrec#19]
Tried to login and fetch model list of the girls i'm following but it wouldn't login.  Keep getting an error message saying couldn't fetch model list. Using Windows 10 - 64 version. Am I doing something wrong?

**Comment by 0xboobface** [comment]
Try restarting the program after entering your login credentials. If that does not work, delete the ctbrec.log, start the program, switch to the followed tab and exit the program after the error occurred. Then post the contents of the logfile here.
Chaturbate uses cloudflare as DOS protection. It may be the case, that the cloudflare challenge prevents your requests.

**Comment by pbradjr99** [comment]
Sweet, the first one worked. Thanks for the quick response, awesome program!

**Comment by 0xboobface** [comment]
You're welcome
