### ISSUE TITLE
Automatically split recordings into segments of configurable length

### ISSUE THREAD

**Issue by AlexeyFinder** [0xboobface/ctbrec#20]
Hi, your program is working very well. Thank you for your efforts! Can you add some functions? For example, it's not enough that the recording automatically stops when a certain recording time is reached.

**Comment by 0xboobface** [comment]
Not sure, if I understood your request. Do you want a time limit for a recording, so that it does not get longer than a certain amount of time? That's is something I might consider.
What is supposed to happen afterwards? Shall the recording stop or switch to another file?

**Comment by AlexeyFinder** [comment]
Yes, the time limit for recording the model. And random, for example from 5 minutes to 20 minutes. Simply, some models leave the room for 1-2 hours of shooting and the camera shoots an empty room. The recording should stop and switch to another model if it entered online or left the private room.

**Comment by 0xboobface** [comment]
> Yes, the time limit for recording the model.

OK
> And random, for example from 5 minutes to 20 minutes. 

Huh? You want to record for a random amount of time between 5 and 20 minutes?
> The recording should stop as usual and the file will be saved to a folder, and also switch to another model if it came online or left the private room.

I think I still don't get, what you are trying to say. You can record different models at the same time and ctbrec will automatically start and stop recording, if a model comes online / goes offline. So there is no need to switch to a different model. There is also nothing, which I can do, if the model leaves the scenes and streams an empty room.

Can you try to explain, what you want to achieve with this functionality?

**Comment by AlexeyFinder** [comment]
While the model will be released offline, it can leave the room and the camera will record an empty room. A random recording time will help to solve this problem, you do not need to record the entire record, and then cut that part when it left the room.

**Comment by 0xboobface** [comment]
We are having some kind of language barrier here 🤔😉
I'll try to summarize what I understood.
You want to have a setting to split up recordings in segments of 15, 20 or xy minutes. The reason is, that some models leave the scene while still streaming and thus an empty room would be recorded. You want to easiliy get rid of these segments and if you have segments of 10,15 or 20 minutes, you can just delete the ones you are not interested in. Is that correct?

**Comment by AlexeyFinder** [comment]
0xboobface, Yes that's right 😉

**Comment by 0xboobface** [comment]
Implemented in version 1.5.1
