### ISSUE TITLE
Followed models - website updated

### ISSUE THREAD

**Issue by idroccolo** [0xboobface/ctbrec#27]
Chaturbate just changes the way it shows models: 
Online are here: https://it.chaturbate.com/followed-cams/
Offline are here https://it.chaturbate.com/followed-cams/offline/
So now CTBREC only shows those who are online.

**Comment by 0xboobface** [comment]
For me it's still the same. Maybe they are currently doing A/B-tests, or they are deploying it partially step by step. Let's observe what they settle with.

**Comment by tarelt** [comment]
for me it happened too, but it's undone by now. I think it was better when showing online only.

**Comment by 0xboobface** [comment]
As of today I have this change, too. If it stays like this, I'm going to add radiobuttons at the bottom of the tab to switch between online and offline models.

**Comment by 0xboobface** [comment]
Version 1.5.3 contains a switch at the bottom of the followed tab to switch between online/offline models
