### ISSUE TITLE
marked as finished but still recording

### ISSUE THREAD

**Issue by swamped15** [0xboobface/ctbrec#30]
When I got home from work today I saw that the program had captured a new recording. It's status was Finished, I merged and deleted the segments and went to the folder in explorer and saw new .ts files being generated and i realized the model was still broadcasting.  Everything before I merged the segments is gone and I was left with a 0kb file.  I still have all the .ts files from after I initiated the merge requests.  When the program merges files what happens to the original .ts files? They don't end up in the recycle bin, is there someway to restore them? 

Thank you, love the program.

**Comment by 0xboobface** [comment]
Sounds like you used an older version. The latest version does the merging automatically in the background while the download is running, so that you end up with one file for each stream. 
> Everything before I merged the segments is gone and I was left with a 0kb file

The merged file was 0kb? Can't imagine what happened there, but as I said, the latest version works differently, so that you shouldn't run into such a problem in the future.

>When the program merges files what happens to the original .ts files? They don't end up in the recycle bin, is there someway to restore them?

Unfortunately not, the files get deleted from hard disk. Unless you use some kind of data recovery tool, they are gone :-(

**Comment by swamped15** [comment]
yeah, when i came here to ask the question i realized i was using an outdated version.  With the new version I still notice that the status of the recording will say finished when its actually still recording. 

Can you recommend a program to merge .ts files?  I usually end up with 4-5 videos for the one model I record due to privates etc. I'd prefer to have only one video per session.   Thanks for the reply

**Comment by 0xboobface** [comment]
> With the new version I still notice that the status of the recording will say finished when its actually still recording.

Hm, I never experienced that. I have to look into that.

> Can you recommend a program to merge .ts files? I usually end up with 4-5 videos for the one model I record due to privates etc. I'd prefer to have only one video per session. Thanks for the reply

I would use Avidemux. It lets you concatenate several video files. If you select copy/copy for the video and audio codec, it remuxes the video without reencoding it. So it is quite fast.
An alternative might be Virtualdub, but I haven't used it for years.
