### ISSUE TITLE
would it be possible to record other sites with it?

### ISSUE THREAD

**Issue by yunyunls** [0xboobface/ctbrec#32]
as title says, would it be possible to record other sites with it?

**Comment by 0xboobface** [comment]
Not at the moment. There is currently no abstraction to support other sites. But I thought about that, too. I assume, most of the sites provide their streams via HLS or DASH streaming, so technology-wise it shouldn't be a problem. What sites were you thinking about?

**Comment by yunyunls** [comment]
> Not at the moment. There is currently no abstraction to support other sites. But I thought about that, too. I assume, most of the sites provide their streams via HLS or DASH streaming, so technology-wise it shouldn't be a problem. What sites were you thinking about?

I was taking about myfreecams  since its the other most popular cam site

**Comment by 0xboobface** [comment]
Version 1.6.0 supports more than one site. The first addition is MFC.
