### ISSUE TITLE
Not creating Playlist file in Client/Server Mode

### ISSUE THREAD

**Issue by doodballot** [0xboobface/ctbrec#34]
It does not seem to be creating a playlist file in the client-server mode.

The server is running on Debian 8 and the client is running on Windows 10.

The recording directories for the model has no playlist file only the .ts files. 

The output for the server has the following ERRORs and WARNs:

18:44:08.380 [Postprocessing[Recordings PATH]//2018-10-14_16-30]** WARN  ctbrec.recorder.PlaylistGenerator - Couldn't determine duration for media_w1955027090_b5128000_5309.ts. Skipping this file.
18:44:10.128 [Postprocessing[Recordings PATH]/2018-10-14_16-38] ERROR ctbrec.recorder.PlaylistGenerator - The MPEG TS stream contains no programs

**Comment by 0xboobface** [comment]
Which version did you use? I made a few changes in the latest version, which might help with this problem. You can also try to generate the playlists by restarting the server as a workaround.
