### ISSUE TITLE
where is config/settings file?

### ISSUE THREAD

**Issue by ellocoaxel** [0xboobface/ctbrec#35]
i accidentally clicked the button next to the minimize and cant get the program to show anymore, i also had another problem before where i runned out of hd space and the program wouldnt let me run the config file anymore and i had to re-install windows to get it to work again, anyways where is it so i can delete it or change it

**Comment by 0xboobface** [comment]
<kbd>CTRL</kbd> + <kbd>r</kbd>
%appdata%\ctbrec
<kbd>ENTER</kbd>

**Comment by 0xboobface** [comment]
I'm sorry, this should be <kbd>WINDOWS</kbd> + <kbd>r</kbd> not <kbd>CTRL</kbd> + <kbd>r</kbd>
