### ISSUE TITLE
Passworded proxy 

### ISSUE THREAD

**Issue by zalupax** [0xboobface/ctbrec#36]
App doesn't work with passworded proxy. How can i fix it? I try 2 diffrent proxy servers

**Comment by 0xboobface** [comment]
How did you configure the proxy (SOCKS, HTTP)? And which proxy servers were you using? Can you see in the proxies log, what is happening?
I didn't really test proxy authentication, because I didn't want to set a proxy up. Maybe we can figure this out together.

**Comment by 0xboobface** [comment]
How did you configure the proxy (socks, http) and which proxy servers did you use? if you have access to the servers logfiles, can you see what is happening?

**Comment by 0xboobface** [comment]
How did you can configure the proxy (http, socks) and which proxies did you test? If you have access to the servers logfiles, can you see what is happening?

**Comment by zalupax** [comment]
[image: 6308ababee2933fe7b551bdb67fc5581.png]
https://altvpn.com/ru/proxy/
In browser proxy works perfectly. And one more thing. When i try socks5 -
error appears too but i dont know exactly which one

пн, 22 окт. 2018 г. в 16:45, 0xboobface <notifications@github.com>:

**Comment by 0xboobface** [comment]
I played around with HTTP and SOCKS servers on my local machine and couldn't login, too. But I think, I got this working now. The next version will include the changes.
