### ISSUE TITLE
Will you be adding other sites?

### ISSUE THREAD

**Issue by RedRhumRedRhum** [0xboobface/ctbrec#40]
Will you be adding other sites? Such as cam4 and bongacams? 
Thanks :)

**Comment by 0xboobface** [comment]
It depends on the site and the technology they are using. Sometimes it not so easy to find out, how to get the actual video stream. But yes, I will add more sites, if possible. I'm already working on camsoda.
Cam4 seems to be quite easy, too. Bongacams seems to be more complicated.
