### ISSUE TITLE
Linux Client Crashes

### ISSUE THREAD

**Issue by hennessyhabit** [0xboobface/ctbrec#46]
When hovering over some previews, the layer with the title of the "stream" will not show up. Outputting consistent java.lang.ArrayIndexOutOfBoundsException, in the terminal until it you get your cursor away from it ("special chars" seem to trigger it like " 👉👌  " ). can lead to crashes. (all of that could be my fault. tell me if so)

**Comment by 0xboobface** [comment]
Can you please post the complete exception? It would make the debugging much easier.

**Comment by hennessyhabit** [comment]
im a little greenhorn but i can pull this info out of the ctbrec.log while running it in the terminal i have no idea yet how to dumb the info. anyways this is the log that it produces i think (i really hope it is) 

2018-11-03 18:47:21,528 WARN [buffering] o.t.m.s.BlockingMultiMTSSource [BlockingMultiMTSSource.java:51] Failed to fix continuity. MTSPacket probably invalid
java.lang.NullPointerException: null
2018-11-03 18:47:21,548 WARN [buffering] o.t.m.s.BlockingMultiMTSSource [BlockingMultiMTSSource.java:51] Failed to fix continuity. MTSPacket probably invalid
java.lang.NullPointerException: null
2018-11-03 18:47:21,590 WARN [buffering] o.t.m.s.BlockingMultiMTSSource [BlockingMultiMTSSource.java:51] Failed to fix continuity. MTSPacket probably invalid
java.lang.NullPointerException: null

**Comment by hennessyhabit** [comment]
How do i find the exception ? (i just can read what seems like a other kind of problem is the ctbrec.log 2018-11-03 18:47:21,528 WARN [buffering] o.t.m.s.BlockingMultiMTSSource [BlockingMultiMTSSource.java:51] Failed to fix continuity. MTSPacket probably invalid
java.lang.NullPointerException: null
2018-11-03 18:47:21,548 WARN [buffering] o.t.m.s.BlockingMultiMTSSource [BlockingMultiMTSSource.java:51] Failed to fix continuity. MTSPacket probably invalid
java.lang.NullPointerException: null
2018-11-03 18:47:21,590 WARN [buffering] o.t.m.s.BlockingMultiMTSSource [BlockingMultiMTSSource.java:51] Failed to fix continuity. MTSPacket probably invalid
java.lang.NullPointerException: null )

**Comment by 0xboobface** [comment]
:) Yeah, this is not related to the error you mentioned. These are just some warning, because the video stream is corrupted. The error should be in the logfile. Unless it is an exception, which is not caught in the code (which might be the case here). Then you can only see it in the console and you would have to copy it from there.

**Comment by hennessyhabit** [comment]
well the terminal only feeds me with java.lang.ArrayIndexOutOfBoundsException (will try some other terminal that give better inside if there is something like that any suggestions ?)

now after more then a hour of running i finaly got the crash that i tryed to provoke that usally happends that log only feeds me java.lang.NullPointerException: null

**Comment by hennessyhabit** [comment]
i got this crash log for you but this is not the array one i pretty sure. 

13:16:04.491 [ThumbOverviewTab UpdateService] DEBUG c.s.c.ChaturbateUpdateService - Fetching page https://chaturbate.com/followed-cams/?page=1&keywords=&_=1541333764491
corrupted size vs. prev_size
/home/user/Desktop/ctbrec/ctbrec.sh: line 7:  3783 Aborted                 (core dumped) $JAVA -Djdk.gtk.version=3 -cp ctbrec-1.6.1-final.jar ctbrec.ui.Launcher

good day sir.

**Comment by 0xboobface** [comment]
Any news on this?

**Comment by hennessyhabit** [comment]
yeah nah i have been messing about with my stuff and borked it from the ground up x/ first downgrading pango seemed to work at the first go then it didnt anymore oh well before i know it hopped distros if you know what i mean. pango seems to be the fix for the array one thank you.

**Comment by 0xboobface** [comment]
I see, distro hopping can be tempting. Usually it doesn't solve the problem, though. Or you swap it for another one :)
Closing this for now.
