### ISSUE TITLE
Non-GUI Version that focuses on performance

### ISSUE THREAD

**Issue by Asynchr0nous** [0xboobface/ctbrec#48]
This might asking for too much but would it be possible to create a version of this script that mainly focuses on performance (i.e to use as less cpu as possible) so that it can be run 24/7 without costing an arm and leg to run. 

in terms cpu usage, this script is not bad at all (as long as you're running in the background) but its hard to say how it will perform when say i'm recording 100 models. of course not all 100 models are going to come online at once but fetching data for multiple models will have impact on cpu. (though i've not looked at how this script does it or how often)

Don't get me wrong this is script is great and i really appreciate your hard work and others that contribute

**Comment by Asynchr0nous** [comment]
just tried that now. the location for server.json file in macOS is `/Users/yourusername/Library/Preferences/ctbrect/`

will see how it goes. thanks

**Comment by Asynchr0nous** [comment]
I've changed the settings so that i can access it remotely but it gives me an error: 
`Problem accessing /. Reason: Not Found`

**Comment by Asynchr0nous** [comment]
off-topic but what does this use in the background to record e.g. with ALL other scripts available they use either ffmpeg or streamlink

**Comment by 0xboobface** [comment]
nothing of that, it's my own implementation

**Comment by 0xboobface** [comment]
> I've changed the settings so that i can access it remotely but it gives me an error:
Problem accessing /. Reason: Not Found

Do have another server running on port 8080? Maybe it helps to run it on another port. You can change the port in the server settings.

**Comment by Asynchr0nous** [comment]
I'm only using port 8888 for a different script. i tried to run this on port 8080 and 9090. what exactly i'm i supposed to see by going to localhost:port?

**Comment by 0xboobface** [comment]
Aha, there is the problem. You don't use a browser, you use ctbrec to connect to the server. Go to the settings and set the record location to point to your server. After a restart you can use it like you would normally do. The recordings are now done by the server instead of the app. When you are set, you can safely exit the app and the server will keep running and reording.

**Comment by 0xboobface** [comment]
@Asynchr0nous did you get it to run? 
I think, the Wiki should have a page about, because it's totally undocumented at the moment.

**Comment by Asynchr0nous** [comment]
`server.sh` is missing in latest version on both linux and macOS.

**Comment by Asynchr0nous** [comment]
>  Go to the settings and set the record location to point to your server. 
So here do I just copy the location of the `server.sh` and paste this where it says "Server under  Record Location" with whatever port?

> After a restart you can use it like you would normally do. The recordings are now done by the server instead of the app. When you are set, you can safely exit the app and the server will keep running and reording.

Am I right to assume that in order to add/remove models i would need to re-open `ctbrec.sh`? Also am I right to assume that the models are recorded 24/7 or is it per session? what i mean by this is that do the models get removed once they stop streaming (so you need to re-add them each time) or do they stay in recording list?

**Comment by 0xboobface** [comment]
There is a new additional package just for the server. This enables me to compile the server with an older version of Java, so that it can be run with Java 1.8 and even 32-bit versions. Another user had requested that. It makes sense, if you want to run it on a raspberry pi or other tiny machines.

**Comment by Asynchr0nous** [comment]
>  Go to the settings and set the record location to point to your server. 

So here do I just copy the location of the `server.sh` and paste this where it says "Server under  Record Location" with whatever port?

> After a restart you can use it like you would normally do. The recordings are now done by the server instead of the app. When you are set, you can safely exit the app and the server will keep running and reording.

Am I right to assume that in order to add/remove models i would need to re-open `ctbrec.sh`? Also am I right to assume that the models are recorded 24/7 or is it per session? what i mean by this is that do the models get removed once they stop streaming (so you need to re-add them each time) or do they stay in recording list?

**Comment by Asynchr0nous** [comment]
Okay so im able to run the server on localhost but where does it actually save your files?

**Comment by Asynchr0nous** [comment]
Okay I'm able to run the server on localhost but can't figure out where exactly its saving these recoridngs?

**Comment by Asynchr0nous** [comment]
okay so i finally managed to run the server on localhost. the recordings produces a folder for the model, followed by another folder named by date and time, which contains 100s of .ts files. when running in normal mode i.e not the server, it creates a folder for the model and then files with appropriate names.

**Comment by 0xboobface** [comment]
Yes, in the client you can download the recording and then you get one big file.

**Comment by Asynchr0nous** [comment]
doesn't that mean you will now have two copies of the same file?

**Comment by Asynchr0nous** [comment]
that makes sense since that is exactly what a client/server is but what i'm a bit confused about is why create multiple .ts files on server and not one big file?

**Comment by 0xboobface** [comment]
The multiple .ts files are recorded exactly how they come from the cam sites. After a recording is finished, the server generates a playlist.m3u8. When you connect to the server with the client and play a recording, it will play the playlist file. So the server is acting as a HLS streaming server. This has the advantage, that scrolling through the video is quite fast and doesn't require to download the whole file.

**Comment by Asynchr0nous** [comment]
That was my thought too.

**Comment by bounty1342** [comment]
I will recommend using rclone for that.

https://rclone.org/
