### ISSUE TITLE
Pause recording

### ISSUE THREAD

**Issue by Dunzura** [0xboobface/ctbrec#50]
When I stop recording, the model dissappears from recording tab. Would it be possible to add a pause recording function which stops recording, but don't delete the model from the list? Or something like that. And there should be a symbol, or different color model name which shows recording is paused.
A pause for x hours or days would be good as well, which automatically continoues recording ater the time has passed.

**Comment by 0xboobface** [comment]
Implemented in efc4719018bcab79975d501a2bd0d45830632ef9, will be in the next version.
