### ISSUE TITLE
Suggestion: allow custom config directory using command line

### ISSUE THREAD

**Issue by 1461748123** [0xboobface/ctbrec#51]
Hi! It would be nice if I can specify the config directly :) I'm running it on my server and want to keep the configs within the directory of the app
Maybe something like this:
`java -cp ctbrec-1.6.0-final.jar -Dctbrec.directory=DIRECTORY -Dctbrec.config=server.json ctbrec.recorder.server.HttpServer`

**Comment by 0xboobface** [comment]
Implemented in 6b16a637f0958eefb5fb0e78340a757614c9fe29, will be included in next version
