### ISSUE TITLE
Setting for post-processing

### ISSUE THREAD

**Issue by 0xboobface** [0xboobface/ctbrec#52]
Add a setting for post-processing of recordings. It's probably enough to provide a simple textfield to put in the program / script to run. Parameters passed to the external program could be
- absolute path to the file
- model name
- site name
- date
- ...

**Comment by SearchAndDestroy** [comment]
I did a quick test and it looks like it's perfectly working. I had to search for a program to convert epoch timestamps to the format I want but otherwise looks great :)

**Comment by 0xboobface** [comment]
Very nice. I was planning to include a sample script (at least for bash). Which operating system are you running? Maybe it's worth it to document different solutions, so that others can benefit from it. I could switch on the wiki feature here on Github to do that.

**Comment by SearchAndDestroy** [comment]
I am on Windows 10 and I am using a really old version of the GNU CoreUtils for the date program from [CoreUtils for Windows](http://gnuwin32.sourceforge.net/packages/coreutils.htm). I can't find any newer precompiled version.

**Comment by 0xboobface** [comment]
I haven't had a look at it, yet, but I was thinking, that powershell could be used for that. I have to play around with that.

**Comment by SearchAndDestroy** [comment]
I think I got it: ```For /F "tokens=*" %a in ('powershell.exe -Command "& {$a=[timezone]::CurrentTimeZone.ToLocalTime(([datetime]'1/1/1970').AddSeconds($args[0])); get-date -date $a -format yyyyMMdd-HHmmss}"  %5') do Set RecDate=%a```
Of course just change the format to what you need :)
Also there is a  problem (at least on Windows) if you try to remove the folder of the recording (%1) because you are in that folder. therefore can't remove it.

**Comment by 0xboobface** [comment]
> Also there is a problem (at least on Windows) if you try to remove the folder of the recording (%1) because you are in that folder. therefore can't remove it.

Oh. This stupid windows locking all files all the time.

**Comment by SearchAndDestroy** [comment]
I know you closed the issue but just another suggestion:
Since the path and the file name are absolutes, why start in the file folder instead of the supplied recording directory?
It would make the post processing script much easier to e.g. remove the folders.
Thanks :)

**Comment by 0xboobface** [comment]
Fixed in ccee14e2ae5e1970531cf7a468057cbe467e1f55
