### ISSUE TITLE
Add CameraPrive

### ISSUE THREAD

**Issue by codexhard** [0xboobface/ctbrec#55]
Hello 0xboobface!

I would suggest this site in a future update: https://cameraprive.com/

Thanks for developing this amazing app.

Thanks!

**Comment by codexhard** [comment]
I have tested only as a guest and registered user, just like you. So ... and that's it! With tokens would I get a third streaming url? So this can be very expensive to test this. Let's just let it go. Thank you!

**Comment by 0xboobface** [comment]
Even in the browser it stops after 1min / 3mins depending on if you are logged in or not. Then it asks you
to buy some tokens to continue. Technically it's no problem to add it, but I don't like the pay per view mentality. 
@Asynchr0nous did you get past the 3 minute limit?

**Comment by Asynchr0nous** [comment]
im not interested in this site as i don't use it or heard of it before but like you said everything is pay per view so not sure what exactly OP wants to record.

**Comment by 0xboobface** [comment]
@codexhard OK, closing this for now. Certainly there are some beautiful Brazilian girls on the site, but with the per-pay-view mechanism, it's not usable for most of us.
And thank you for the :coffee:  :smiley:
