### ISSUE TITLE
BongaCams captcha not usable

### ISSUE THREAD

**Issue by 0xboobface** [0xboobface/ctbrec#58]
The BongaCams login shows a captcha stating "your machine is unknown system" or something like that. This happens after not using it for a longer time (for example if you shut ctbrec down for the night and restart it the next day). Unfortunately the shown captcha is not working properly in JavaFX's webengine. The only way to solve this problem is to login with a browser. After doing that, the login does not show the captcha, but only the login dialog and afterwards the login cookies work, so that no login has to be done at all.

**Comment by Xploit3r** [comment]
I have a question. I am using CTB Rec without actually creating an account using it on Bongacams. Do we actually need to supply our credentials to the application for recording the streams from Bongacams?

I am able to record it right now without actually entering any login information.

**Comment by 0xboobface** [comment]
Credentials are only needed, if you want to use the Friends tab or the tipping feature.

**Comment by cmdicksonau** [comment]
> The BongaCams login shows a captcha stating "your machine is unknown system" or something like that. This happens after not using it for a longer time (for example if you shut ctbrec down for the night and restart it the next day). Unfortunately the shown captcha is not working properly in JavaFX's webengine. The only way to solve this problem is to login with a browser. After doing that, the login does not show the captcha, but only the login dialog and afterwards the login cookies work, so that no login has to be done at all.

Thanks for that. Now which browser do I need to use? Bongacams is logged in via my default - Chrome Beta however the captcha still gets displayed...
