### ISSUE TITLE
Does not auto-record models from Followed list?

### ISSUE THREAD

**Issue by Mush-r00m** [0xboobface/ctbrec#6]
Hello, after logging into the program, followed list populated. But when models were online that i have followed they are not auto-recorded even after waited an hour. seems i must manually select models to record even when i have them followed.

Would you be able to add an option in setting to auto-record models from followed list? and have it check for online models every 60 seconds for example.

**Comment by 0xboobface** [comment]
So you want to record every model in your followed list? Isn't that a bit much, or do you only have a few models in the followed list?
The feature you are talking about, is the "Recording" tab. Every model, which is listed there, is automatically recorded once it comes online. You can add models to this list by right clicking and selecting "Start recording".

**Comment by Mush-r00m** [comment]
Yes, i would like  to record every model on my followed list automatically, It can be a option in settings to be turned on or off.  I follow alot of models. And i have the connection speed and disk space ;) its useful so that you can leave the program running and not interact with it much :)

**Comment by 0xboobface** [comment]
Wow, that's quite radical :)
Did you do a test with the current version? I'm mean, did you record every model, which is currently online in your followed tab? If that works for you and you don't run into problems with chaturbate, then I can think about it. But my feeling is, that this is a uncommon use case.

**Comment by Mush-r00m** [comment]
No i have not tried to record more than a few models at a time with your software but i can. And its actually a common use case. It allows people to let the program run and have little interaction with it since all they have to do is follow a girl. Hence the popularity of chaturbate-node, which auto downloads all models on your followed list. Very popular and discussed across certain forums.

**Comment by 0xboobface** [comment]
I implemented this in 1.4.0. Please try it out and let me know, if you face any problems. I have many models in the followed list, so I can test it without maxing out my internet connection.
