### ISSUE TITLE
Docker image for ctbrec

### ISSUE THREAD

**Issue by 1461748123** [0xboobface/ctbrec#61]
I built an image for ctbrec. I'm using it on my Synology NAS and will maintain the image when the software is updated.
Link: https://hub.docker.com/r/1461748123/ctbrec/

**Comment by Asynchr0nous** [comment]
I was thinking about asking if it was possible to do so thanks for this.

**Comment by 0xboobface** [comment]
Nice, works like a charm. I enabled the Wiki function (I hope it's editable for github users). Feel free to document it there, so that people can find it more easily.

**Comment by 1461748123** [comment]
> Nice, works like a charm. I enabled the Wiki function (I hope it's editable for github users). Feel free to document it there, so that people can find it more easily.

Thanks, I will do that when I have time :)

**Comment by sylinen** [comment]
Dunno if this is just an Unraid issue (probably is, I've had problems with its network bridging before), but I get immediate exceptions thrown on starting your Docker container. 
[log.txt](https://github.com/0xboobface/ctbrec/files/2601776/log.txt)

**Comment by 0xboobface** [comment]
> Caused by: java.net.ConnectException: Connection refused (Connection refused)

Looks like a firewall problem to me.

**Comment by sylinen** [comment]
Doubtful. I'm running another instance on an Ubuntu VM without issues.

**Comment by Asynchr0nous** [comment]
are you running these on cloud by any chance?

**Comment by sylinen** [comment]
nope

**Comment by 0xboobface** [comment]
> www.myfreecams.com/0.0.0.0:80

The 0.0.0.0 IP here also looks suspicious. Does the name resolution work in the container?

**Comment by TheSpixxyQ** [comment]
Can you please update that image? You're still using old 1.9.0 version which is not working. Thanks

**Comment by 0xboobface** [comment]
FYI https://github.com/0xboobface/ctbrec/pull/136
