### ISSUE TITLE
Make download location configurable

### ISSUE THREAD

**Issue by jamesjonesfor3** [0xboobface/ctbrec#62]
- myfreecams usernames should not be case sensitive. I added a model's name correctly but it didn't record because of capital letters in her name
- right clicking on a recording should give a context menu option: open containing folder
- small convenience: let users input "mfc:username" instead of only "myfreecams:username". "cb:username" instead of only "chaturbate:username"  
- option to not put each new recording in it's own seperate folder. The files are already named with the timestamp, it feels unnecessary to make seperate folders with timestamps for each recording.

**Comment by VeganButcher** [comment]
I agree with all these suggestions but especially not putting each file in its own folder. Right now I don't think it's even possible for it to automatically record more than 1 file in each folder, it's very inconvenient and seems pointless.

It would also be nice if there was an option to group all recordings into a single directory instead of having one for each model.

**Comment by 0xboobface** [comment]
> myfreecams usernames should not be case sensitive

Fixed in bd1522f615990a55b554e9f17df2e4c666a11050

**Comment by 0xboobface** [comment]
>right clicking on a recording should give a context menu option: open containing folder

Added in 5df5b4a

**Comment by 0xboobface** [comment]
> small convenience: let users input "mfc:username" instead of only "myfreecams:username". "cb:username" instead of only "chaturbate:username"

I didn't implement this exact feature, but the box now does auto completion for the site name. That should make it easier. Added in 60e81c5dbf859db5674ce5f25e562126f9d773f4

**Comment by 0xboobface** [comment]
> option to not put each new recording in it's own seperate folder. The files are already named with the timestamp, it feels unnecessary to make seperate folders with timestamps for each recording.

A similar request is discussed in #44 . I think I could add some predefined options in a drop down menu, but I won't implement a fully configurable (with variables) structure.
