### ISSUE TITLE
Models seem missing

### ISSUE THREAD

**Issue by illeon** [0xboobface/ctbrec#64]
A lot of models don't seem visible on both mfc and chaturbate, I was looking for some models from South America but I could not find any not even the top rated ones. What could be the problem?

**Comment by Asynchr0nous** [comment]
it only shows models currently online. also you need to go to next page (at the bottom) to see more models

**Comment by illeon** [comment]
I was using the search bar and looking for models I know who are online at the moment but they don't show up

**Comment by illeon** [comment]
That was the problem, thank you. How do I find which page a model A is on?

**Comment by Asynchr0nous** [comment]
currently there isn't so you're stuck with going through all pages.
