### ISSUE TITLE
Suggestion: Look for the settings.json file in the program directory first

### ISSUE THREAD

**Issue by bj73** [0xboobface/ctbrec#65]
This is mainly for the Windows build but is it possible to have it look for the settings.json file in the program directory first before it goes looking in other places?

Mainly so you can have it self-contained, (stick it on a flash drive, etc), and you can connect to more than one server by just having another directory with the program and a different settings.json file.

Currently you have to swap settings files in %APPDATA%\ctbrec if you want to connect to another server.

Or any other idea that enables everything relating to the program and what sites/servers/usernames/passwords/etc it's set for, to be stored in one directory.

**Comment by 0xboobface** [comment]
You can create a file `ctbrec.l4j.ini` right next to ctbrec.exe with the following content:
```
-Dctbrec.config.dir=c:\save\my\config\here
```
Relative paths should work, too:
```
-Dctbrec.config.dir=.\conf
```

**Comment by bj73** [comment]
That's great, thanks!
