### ISSUE TITLE
Delay recording and/or set recording limits?

### ISSUE THREAD

**Issue by richvalens** [0xboobface/ctbrec#66]
First of all, great piece of work! Can you accept donations via PayPal? I haven't set up any of your donation methods yet. If not, I will try and do so as I believe your project has great potential. 

Prior to finding your software, I developed a series of batch scripts using existing projects which allows me to delay the start of recordings as well as limit them. Why? Couple of reasons ... 

1) Naturally I most interested in watch the good part of the show and often it happens quite a while after the model comes online. My scripts can delay a recording for x minutes after a model comes online. 
2) Since I have bandwidth restrictions with my ISP, I tend to limit the show to say one hour or 90 minutes as these recordings can consume quote a bit of bandwidth. 

With my scripts I have been able to do this just fine but is not GUI based - which has its negatives as well as positives (performance). I love your interface and was wondering if that may be something that could be considered in the future. I know some recorder implementations actually monitor when a room user count is trending upwards as a gauge of a show starting and starts the recording at that point and then stops it when users start dropping. That is a terrific feature.

The issue with many of these implementations is that the author stops supporting after some time when  plugin needs updates so it breaks. Hopefully you will keep supporting/enhancing. I am sure that as features are added, more users will jump on your projects. I happy to support your efforts.

If not possible, thank you regardless for what you have developed and look forward to enhancements you have time for.

**Comment by 0xboobface** [comment]
Those are definitely interesting ideas. I can vision a version of ctbrec, where you can define different triggers when to start a recording.

Regarding 1: What do those other scripts do, when the stream is unsteady (for example if the model has a bad connection or does short privates here and there)? That would reset the counter. I guess we would need a threshold, when to consider a stream as finished / still going.

Regarding 2: There is already a similar feature with the splitting of recordings. So, stopping the recording after x minutes isn't a problem. The problem I see is, that the mechanism, which monitors the models, then would trigger the next recording right away. I would have to make that mechanism smarter, too.

Thanks for considering a donation. You can use 0xboobface@gmail.com for PayPal.

**Comment by richvalens** [comment]
See response at end of question - Regarding 1: What do those other scripts do, when the stream is unsteady (for example if the model has a bad connection or does short privates here and there)? That would reset the counter. I guess we would need a threshold, when to consider a stream as finished / still going. 
Response - It's hokey but what I do is capture the time the recording starts. When it stops due to privates or going offline, it captures the delta and then restarts with the adjusted time frames. Same thing  when connection is not stable. Not working 100% as the errorlevels returned by the software are not granular enough but it I am getting there. It's not perfect but only play with it in my spare time and does good enough for now.  With my luck by time I get it right, the plug in will break and will have done if for nothing :(.

Regarding 2: There is already a similar feature with the splitting of recordings. So, stopping the recording after x minutes isn't a problem. The problem I see is, that the mechanism, which monitors the models, then would trigger the next recording right away. I would have to make that mechanism smarter, too.

Response. Yes, saw that feature and figured it could be adapted if you saw benefit.

Oh -- one minor suggestion, the thumbnail refresh would be nice if it could be adjustable or turned off. 

Thanks for considering it. I will make a donation later today and will do more as project matures for sure.  Will be coming from another account starting with cm*

Thanks

**Comment by 0xboobface** [comment]
> the thumbnail refresh would be nice if it could be adjustable or turned off

Switch added in 97d3be0b98914a8e71e79b90deace59140236fac

**Comment by 0xboobface** [comment]
Closing this. I created a new issue #91, which includes your ideas.
