### ISSUE TITLE
Suggestion: Ability to set the default tab when program started

### ISSUE THREAD

**Issue by bj73** [0xboobface/ctbrec#68]
For a couple of scenarios:
1) Those who already have a list of their favourite models, (or ones set to record), might just want to see the status of them when the program starts.
2) From a NSFW, (Not Suitable For Wife), perspective it's a little less embarrassing, (or self-preserving), to have it open at the Recording or Recordings tab than have a page full of scantily clad women, men, etc, appear.

**Comment by 0xboobface** [comment]
Added in 2202dc969f7c82d22d43c57c4b01622cdf6107a1
