### ISSUE TITLE
Problem recording & suggestion

### ISSUE THREAD

**Issue by aaea121** [0xboobface/ctbrec#69]
If a recording for a model drops very quickly (when files are <1mb) I noticed that the program will not try recording that model again, as it thinks it still is recording.

I'd also like to suggest two features while I'm here:

1. Disk space check - stop recording if disk space falls below a certain threshold

2. Model check interval - set the delay to check if models are online

Thanks for making this

**Comment by Septan** [comment]
I also having a recording issue, I don't know if same as user above. When put split recordings after so many x minutes. It making small little files that are even a second long. If disable the split x minutes it seems to work fine.

**Comment by 0xboobface** [comment]
> If a recording for a model drops very quickly (when files are <1mb) I noticed that the program will not try recording that model again, as it thinks it still is recording.

Interesting observation. Not sure why that happens. I have to review the code and see, if I can find something. Unfortunately this also might be hard to test.

**Comment by 0xboobface** [comment]
> If a recording for a model drops very quickly (when files are <1mb) I noticed that the program will not try recording that model again, as it thinks it still is recording.

Were you running ctbrec in standalone or in client / server mode?

**Comment by aaea121** [comment]
standalone

it's not super common but common enough for me to notice occasionally when I'm paying attention and manually checking

**Comment by 0xboobface** [comment]
I'm not sure, if I fixed this, but I did a lot of tweaking to how downloads are handled and especially how errors during downloads are handled for #70 . Chances are, the changes also fixed this problem. I'll leave this open, so that we can test with the next versions. If we don't see the problem anymore, we can close this issue.
