### ISSUE TITLE
Select quality

### ISSUE THREAD

**Issue by YDdraigGoch** [0xboobface/ctbrec#7]
Hey. Is it possible to be able to select the quality of the streams? Sometimes they put their bitrate too high for 1080p and my bandwidth suffers as a result.

On other programs on GitHub, where they use streamlink, I manage to tweak the code so I can choose lower quality streams link 480p.

**Comment by 0xboobface** [comment]
Implemented in 98cefacae35bc84c4bfdf54149275043343ed1ea. Will be part of the next version.
