### ISSUE TITLE
dark mode of the app

### ISSUE THREAD

**Issue by Sojiro84** [0xboobface/ctbrec#71]
I would like to see a dark mode version of the app as well. That way, browsing in the evening is less straining on the eye.

**Comment by 0xboobface** [comment]
The GUI definitely supports that, because the styling is CSS based, but I imagine, it is quite some work to create a new skin for the app. I'll have a look at it.

**Comment by 0xboobface** [comment]
It was much easier than expected. The next version will have color choosers in the settings.
Implemented in 84dfeb9.

**Comment by Sojiro84** [comment]
I am happy to hear that it wasn't much work. Thanks for the amazing app. I was looking for a good program to do stuff like this on Linux. You are a lifesaver. Now I have no more reason to stay on Windows.

I will be getting some tokens through your app. 😇
