### ISSUE TITLE
Split recordings produce small files

### ISSUE THREAD

**Issue by 0xboobface** [0xboobface/ctbrec#72]
Orignal message by Septan:
> When put split recordings after so many x minutes. It making small little files that are even a second long. If disable the split x minutes it seems to work fine.

**Comment by mrpulpy** [comment]
I've been seeing the same issue since 1.10. With split recordings disabled it records as expected in 1.10 and 1.11, and when I rolled back to 1.9 split recordings worked fine again.

**Comment by 0xboobface** [comment]
Fixed and improved in 403c1ed
