### ISSUE TITLE
Remember selected columns and sub-tabs and remember settings when force quitting

### ISSUE THREAD

**Issue by nim56** [0xboobface/ctbrec#74]
Thank you for this software.
I have a few minor improvement suggestions:

- Remember selected column organization and (maybe?) selected sub-tabs of each tab when you re-launch the software.

- When you shut down computer without closing the software manually or when you quit the software using task manager, it doesn't save the changes made to recording and settings tabs during the last session.

Thanks.

**Comment by 0xboobface** [comment]
I have added the save and restore of the table states in b869c4a.
All settings (at least I hope so :smile: ) including the recorded models list are now saved immediately. Added in e5ff778 and faf6240.

At the moment the last selected tab / sub tab is not saved. But I have added a setting to define, which tab is opened at the start of the application (see #68).

All changes will be part of the next version.
