### ISSUE TITLE
MFC Model Missing

### ISSUE THREAD

**Issue by LostSoul99** [0xboobface/ctbrec#75]
I have one model on my MFC friends list that does not show up in ctbrec when she is online and broadcasting on MFC.  I even did a search on every page and nothing.  This is a link to her particular profile.  

https://profiles.myfreecams.com/BlueAngelLove

**Comment by 0xboobface** [comment]
Did you try to add her manually to the list of recorded models? And if so, did the recording work then?
MFC sends a list with all online models at the beginning of a session. Afterwards updates are transmitted whenever a model comes only. I can't think of reason she wouldn't show up, if she shows up on MFC's website.

**Comment by LostSoul99** [comment]
I have added her manually and the program does not know she is online.  It's really strange that with this particular model it doesn't see her.  I have another program that I was using before ctbrec that uses an exe version of mfc node that records her just fine.  She is actually online right now but it doesn't see her.

**Comment by 0xboobface** [comment]
Mmh, that's weird. I added here to my list, when I replied to your first post. I have 2 recordings from about 8h ago, which matches the time of your response. So, it worked fine for me. Could be it some kind of selective blocking (geoblocking, banning, free vs. premium or something like that)?

**Comment by LostSoul99** [comment]
Well this is really strange then, I can see her fine if I'm logged into MFC and it is with a premium account.  I will try a different MFC account and see what happens.  I even tried on 2 different PC's.

Thanks for checking on it for me.

**Comment by LostSoul99** [comment]
Using a different account fixed the problem with this model.  I now just noticed she doesn't always show online on that other account even in my browser even though she is on my friends list.  I'm not blocked by her because if I find her in my offline friends I can enter her room when she is online.  So strange but problem solved, please close.
