### ISSUE TITLE
A few QOL features

### ISSUE THREAD

**Issue by quetzalsly** [0xboobface/ctbrec#76]
- [x] Being able to just paste an url in without typing chaturbate:model.
- [x] Being able to tick the boxes for pause instead of right click and pause.
- [x] A pause all button.
- [x] Hover over an item in the record list and it pops up a thumbnail of the last video frame (updates every 5 seconds). This would allow us to see if the model is doing something that I want to record, if she is being boring I can just stop recording her.
- [x] Being able to select multiple items in the record list with shift or control.

**Comment by jamesjonesfor3** [comment]
To add to the first point, alternate inputs that make sense would be nice. 
Instead of "myfreecams:username"

- https://www.myfreecams.com/#username
- https://profiles.myfreecams.com/username

Instead of "chaturbate:username":
- https://chaturbate.com/username

**Comment by quetzalsly** [comment]
If it's too much work to add url parsing, maybe a simple dropdown menu would work and then being able to just paste in the modelname. This way at least there is no extra effort to the user to keep typing the chaturbate: prefix.

**Comment by 0xboobface** [comment]
> Being able to just paste an url in without typing chaturbate:model.

Added in afd5d3c

**Comment by 0xboobface** [comment]
> A pause all button.

Added in 0bd655b

**Comment by 0xboobface** [comment]
> Being able to select multiple items in the record list with shift or control.

Added in 40b3b78

**Comment by 0xboobface** [comment]
> it pops up a thumbnail of the last video frame

Added in 754271c. But it's not showing snashots every 5 seconds, but instead plays back the stream
with the lowest quality without audio, like for example bongacams does it. I hope the internal player is
stable enough and works on all platforms. Fingers crossed :crossed_fingers: :fearful:

**Comment by quetzalsly** [comment]
Awesome stuff!
