### ISSUE TITLE
chaturbate.com

### ISSUE THREAD

**Issue by zslumantony** [0xboobface/ctbrec#78]
Sir, when chaturbate models goes pvt mode recording will stopped.
pls i need when chaturbate models goes pvt mode recording. pls sir fix this issues.

**Comment by RedRhumRedRhum** [comment]
It cannot be done. PVT mode is an encrypted video stream that cannot be unencrypted unless you are in the models room and paying tokens to see the video feed.

**Comment by zslumantony** [comment]
sir i will pay if u suggest any method or software for download pvt mode
chaturbate.com.. plsss sir.. guide me.

**Comment by 0xboobface** [comment]
Technically it might be possible to record privates, but I'm not interested. I also don't have the tokens to join privates and reverse engineer how they work, so that I can implement that in ctbrec.
Also, would you record all privates, or would it be a manual process. Because, if you do it automatically, you would burn through a lot of tokens, I image.

**Comment by zslumantony** [comment]
Sir i cant understand ur mail. pls send simple english reply sir.. first
line i understand sir.. otherlines r not understand sir.. pls sir..

**Comment by zslumantony** [comment]
Sir u said "Technically it might be possible to record privates, but I'm
not interested."
Sir please i will pay for that pls i can manually do what u guide
sir please do this help sir.
Thanks sir

**Comment by bj73** [comment]
Don't think that's going to be possible without implementing something like an rtmpsuck transparent proxy, the stream is encrypted and you need to be logged in and on the access list to be able to view it and there's 3 ways of doing that:
- Tip the requested amount, (repeatedly for group shows),
- Be on the automatic access list, (eg. some Fan clubs have automatic access),
- The broadcaster manually adds you for the session.

Also, you can only have a single presence in a chatroom, so if you're watching a Private/Hidden, (or even Public), in one browser and then log into the chatroom from another browser/application, the original log in will be kicked from the room.

The easiest to implement would be if you're in a Fan Club that automatically allows access for Hidden Cam sessions (eg. CrazyTicket), a setting against relevant models could indicate this so when the program detects that the model is Hidden, it logs in, performs the handshaking, and initiates recording.

Given that the broadcaster can see who is on the viewer list it's going to look a little suspicious that this one Fan Club member only always appears when there is a Hidden session and doesn't interact, (considering there's generally a notification when a Fan Club member enters the room along with attendant responses from other fans, mods, and the broadcaster).

**Comment by bj73** [comment]
> Password-locked rooms should be similar. I believe you only need to enter the password/room once and then CB will cache your access and let you back in without another prompt. I'm not 100% sure on that though since it's been a while. The cache is probably not forever but it should be good enough to login/access the room in a full browser and then have CTBRec get in on its next check.

It doesn't work that way, you need to enter the password to access the room in every browser/program you use.  Just entering it through a browser, (eg. Firefox), won't let you automatically view it in, for example, Chrome without entering the password again.  (At which point you'd be kicked out of chat in Firefox - only one presence in the room under a given username at a time.)

I'm a verified broadcaster so it's pretty easy to test, ie. broadcast, (eg. as 'fred'), and then open two browsers, (Edge, Vivaldi), and log into the room under the same username, (eg. 'harry'), you'll be asked to enter the password each time.
The access is negotiated with each client, (browser, program, etc), you use to access the room, it's not cached on the server.  The server only keeps a list of usernames who are allowed access to the stream.
