### ISSUE TITLE
No main manifest attribute

### ISSUE THREAD

**Issue by YDdraigGoch** [0xboobface/ctbrec#8]
Hello. Me again. When I try to use on ubuntu, I make the jar an executable but when I double click it won't load. Then if I try 
> java -jar ctbrec-1.2.0-final.jar 

I get "no main manifest attribute, in ctbrec-1.2.0-final.jar

Thanks again

**Comment by 0xboobface** [comment]
Use the ctbrec.sh shell script to launch it.
