### ISSUE TITLE
"Couldn't load settings" when launching the program

### ISSUE THREAD

**Issue by wawakaka17** [0xboobface/ctbrec#88]
Hello there & thanks for this useful program.
It was working well on a previous release, but after I unzipped the latest version (1.12.1-final), I'm getting this error message whenever I try to launch the program: "Couldn't load settings".
Any suggestions?

I'v used the jre version for Win64

**Comment by 0xboobface** [comment]
First of all, could you please attach the ctbrec.log file here. It is located next to the ctbrec.exe. It would also be great, if you could share your settings file.
This is, how you find your settings file.
<kbd>Windows</kbd> + <kbd>R</kbd>
Type in `%appdata%` and press <kbd>enter</kbd>
Open the ctbrec folder
You should see a settings.json
If you want to attach it here, make sure to **remove your credentials first!!!**

To fix the problem, just rename the settings.json to something else. Unfortunately **this will reset your settings**, but ctbrec should start again. If ctbrec started again and you are brave, you can copy the models part from the old, renamed file to the new one. Then you get your recorded models back.

**Comment by wawakaka17** [comment]
Thank you for that solution. the renaming settings json file worked well, but when I tried to copy/paste the models in the new one, the problem got back. I used Word for that (maybe it's not the best to do it? but I've noticed that the models were added in the new one, when I showed it in Chrome). 
Also, I suppose we can't sign in to our account anymore in the new version to retrieve the followed models? (I have a very old one where there was just CB with sign up option...)

**Comment by 0xboobface** [comment]
> First of all, could you please attach the ctbrec.log file here. It is located next to the ctbrec.exe.

Can't help you, if you don't give more details.

**Comment by wawakaka17** [comment]
Oh. I'm sorry, forget to do this. Here are the 2 requested files.
[ctbrec.log](https://github.com/0xboobface/ctbrec/files/2633339/ctbrec.log)
[Settings.txt](https://github.com/0xboobface/ctbrec/files/2633343/Settings.txt)

**Comment by 0xboobface** [comment]
These look like the files after you fixed the problem. (The log file gets overwritten on start.) Do you still have the broken settings?

**Comment by wawakaka17** [comment]
I'm afraid I deleted them. Thanks for your help for now. I'll see if the problem come again when updating & let you know.

**Comment by wawakaka17** [comment]
Hi,

I think I was adding them by searching the names. Hope that helps...

**Comment by 0xboobface** [comment]
> I think I was adding them by searching the names

With the search functionality on the overview tabs, or with the text input on the recording tab?

**Comment by wawakaka17** [comment]
Search functionality on the overview tabs, generally.
