### ISSUE TITLE
Any chance of getting a 32-bit Windows build?

### ISSUE THREAD

**Issue by uNderdog101** [0xboobface/ctbrec#9]
I have an old computer running Windows 7 32-bit that I'd like to use to capture a couple of streams, but there's no 32-bit version. Any chance you could release one?

**Comment by 0xboobface** [comment]
Just released 1.3.0, which includes a 32 bit version. I'm not going to list it on the homepage, but you can always go to the github release page and find it there.
https://github.com/0xboobface/ctbrec/releases
