### ISSUE TITLE
24 hr Model Recording/View Count Recording

### ISSUE THREAD

**Issue by guestbuy5** [0xboobface/ctbrec#90]
First off, excellent program! I have two suggestions I wanted to throw out, which I have no idea how hard or easy it would be to implement.

1. Sometimes it's nice to record a model once off, but not have her stay on your always-record list. Would it be possible to have a 24 hr watch on her, then automatically fall off the record list? Essentially a temporary watch list?

2. Start recording a selected model when viewer count gets a certain threshold? Obviously this could be a global setting for each site or more preferably adjustable per model. 

Thanks for your hard work and quick releases. Don't burn yourself out!

**Comment by 0xboobface** [comment]
Closing this. I created a new issue #91, which includes your ideas.
