### ISSUE TITLE
New type of Models View, automation of recordings and customization of paths and filenames. (Suggestions)

### ISSUE THREAD

**Issue by aand101** [0xboobface/ctbrec#95]
Hello!

First of all I would like to thank you for creating this really amazing app and secondly, thank you for sharing your code with all of us. THANK YOU VERY MUCH!

I would like to present some suggestions and if possible see them implemented in the future in the application. I will divide them into 3 parts:

1)DISPLAY OF THE MODELS IN A TABLE WITH DETAILED INFORMATION
In addition to the view that already exists, in the form of thumbnails, I'd like to suggest a second view, "Detailed View." This mode would consist of a table with profile information of the Models. I will always use MyFreeCams as an example, as it is the website I know the most.
The idea is a table where in each line we would have the Model information. For each column we would have the type of information, something like for example:
_column 1 - could use the Model live thumbnail or your profile image (maybe applied when she is away or in private chat)
2 - Model ID
3 - Model name
4 - indication if the Model is "new"
5 - indication if Model is on the favorites list
6 - status (free, away, private chat, etc... or recording/capturing)
7 - continent or region
8 - country
9 - city
10 - ethnicity
11- age
12 - occupation
13 - blurb
14 - topic
15 - tags_

I do not know if all the websites supported by ctbrec make this information available (how many or which), as I have already mentioned, I know the MyFreeCams provides these informations. In the case of MyFreeCams specifically, there are other items like "miss mfc", "camscore", which can also be added.
The table can be fully customizable, with width and position of the columns adjusted using drag and drop and also order the Models by clicking on the corresponding column header.
It is also interesting for the user to choose how many and which columns to display.

2)AUTOMATIC CUSTOM RECORDING
Another idea is automatic recording based on user presets and using the information/data I described above.
For example, something like:

_RECORD AUTOMATICALLY ONLY:
() by continent(s)/region(s): [insert continent/region or continents/regions separated by commas]
() by country(ies): [same procedure/example above]
() by ethnic(s): [same procedure/example above]
() by age: () equal to [insert age]
           () less than [...]
           () more than [...]
           () between [...] and [...]
() if the occupation contains the keyword(s): [insert keyword(s) separated by commas]
() if the blurb contains the keyword(s): [same procedure/example above]
() if the topic contains the keyword(s): [same procedure/example above]
() if the tags contains the keyword(s): [same procedure/example above]
() if the Model is "new"_

Other items can also be added.
This is just a schematic example where "()" represents "checkboxes" and "[ ]" represents "text entries".

It is also interesting to use a kind of limiting the number of simultaneous recordings (the user indicates the maximum number of captures allowed), useful for cases where a large number of Models are automatically obtained or if there are a large number of Models online at the same time in your favorite list.

3)CUSTOMIZATION OF THE PATH FORMATS AND NAME OF THE FILES CAPTURED
Also based on the data previously mentioned, I suggest the possibility of customizing both the path and the name of the file created in recording/capture.
Exemplifying:
_In my folder "Recordings", let's say I want to separate my captures from "favorite list" and those from my "automatic recordings";
In the "favorites list folder" separate them by country;
In the "country folder" separate them by "age", then "Model name" and then having files in hour-minutes format, would look something like:_

_... \ Recordings \ $favorites$ \ $country$ \ $age$ \ $modelname$ \ $hh-mm$.ts_

_hipothetically:_

_...\Recordings\Favorites\United States\25\CuteBabe6969\12-30.ts_

Above is just a simple example. The idea is to have keywords for the various data: website name, favorites, autorecording, ID, model name, new, continent or region, country, city, ethnicity, age, occupation, etc... for date and time: DD, MM, YYYY, hh, mm, ss, 12h, 24h, etc... that together using " \ " to create subdirectories and other characters can generate a huge number of possibilities and customization of locations and filenames.

Well, these are some suggestions, I am extremely grateful if you can consider them and again thank you for the wonderful job shared with all of us!

**Comment by 0xboobface** [comment]
The next version will have a tabular view for MFC.
I'm not going to implement the different triggers decribed under 2. in the near future, because most of that data is only available in memory for MFC. For the other sites I would need to request the data for each model and that is way too much.
3. has been discussed.
