### ISSUE TITLE
Delete cookies when credentials are changed

### ISSUE THREAD

**Issue by swamped15** [0xboobface/ctbrec#99]
When I originally began using the program I setup a separate chaturbate account to follow only the models that I wanted to record. With the enhanced features that have come about I want to sign in to my regular account.  I am using ctbrec-1.13.0-win64-jre. I have changed my log in information and restarted the program and while the log in information shows on restart the followed tab has not updated.  I'm not sure if the program failed to login or it failed to update the followed tab.

**Comment by RedRhumRedRhum** [comment]
Happened to me yesterday as well. A few hours later it seemed to work again. 
If you follow another room within the program, you will get an error message about age verification until it sorts itself out at random.

**Comment by 0xboobface** [comment]
Probably ctbrec is still using old cookies for the login. Try the following:

Close ctbrec
<kbd>WINDOWS</kbd> + <kbd>r</kbd>
Type in `%appdata%\ctbrec`
<kbd>ENTER</kbd>
Delete `cookies-chaturbate.json`

**Comment by swamped15** [comment]
bingo, thank you!
